personal_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from personal_site import settings

urlpatterns = [
    path('', include("site_about_us.urls", namespace="about_us")),
    path('', include("site_resume.urls", namespace="resumes")),
    path('', include("site_blog.urls", namespace="blogs")),
    path('', include("site_work.urls", namespace="works")),
    path('', include("site_contact.urls", namespace="contact")),
    path('admin/', admin.site.urls),
]
handler404 = 'personal_site.views.view_404'
handler403 = 'personal_site.views.view_403'
handler400 = 'personal_site.views.view_400'
handler500  = 'personal_site.views.view_500'

if settings.DEBUG:
    # ADD ROOT STATIC FILES
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # ADD MEDIA STATIC FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_blog/urls.py
from django.urls import path
from .views import BlogsList, blog_detail, BlogsListCategory, like, unlike

app_name = "blogs"

urlpatterns = [
    path('blogs/', BlogsList.as_view(), name="blog_list"),
    path('blogs/<category_name>/', BlogsListCategory.as_view(), name="blog_list_category"),
    path('blogs/<blogId>/<name>/', blog_detail, name="blog_list"),
    path('like/<blogId>/', like, name="like_blog"),
    path('unlike/<blogId>/', unlike, name="unlike_blog")
]

site_blog/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone
import os
import random

from site_blog_category.models import BlogsCategory


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    random_num = random.randint(1, 989999999)
    name, ext = get_filename_ext(filename)
    final_name = f"{random_num}-{instance.title}{ext}"
    return f"blogs/{final_name}"


class BlogsManager(models.Manager):
    def get_active_blogs(self):
        return self.get_queryset().filter(active=True)

    def get_by_id(self, blog_id):
        qs = self.get_queryset().filter(id=blog_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    def get_blogs_by_category(self, category_name):
        return self.get_queryset().filter(categories__name__iexact=category_name, active=True)


class Blogs(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان", default="عنوان")
    description = models.CharField(max_length=400, verbose_name="توضیحات کوتاه", default="توضیحات کوتاه")
    body = RichTextField(blank=True, null=True, verbose_name="بدنه اصلی")
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True,
                              verbose_name="تصویر اصلی")
    categories = models.ManyToManyField(BlogsCategory, blank=True, verbose_name="دسته بندی وبلاگ")
    like = models.ManyToManyField(User, related_name="BlogsLikes", blank=True, verbose_name="لایک")
    time = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    active = models.BooleanField(default=False, verbose_name="فعال / غیرفعال")

    objects = BlogsManager()

    class Meta:
        verbose_name = "بلاگ"
        verbose_name_plural = "بلاگ ها"

    def __str__(self):
        return self.title

    def get_image_or_default(self):
        try:
            return self.image.url
        except:
            return '/static/default/background-image.jpg'

    def get_absolute_url(self):
        return f"/blogs/{self.id}/{self.title.replace(' ', '-')}"


class CommentManager(models.Manager):
    def get_active_comment(self):
        return self.get_queryset().filter(active=True)


class Comment(models.Model):
    blog = models.ForeignKey(Blogs, on_delete=models.CASCADE, related_name="comments", verbose_name="بلاگ")
    name = models.CharField(max_length=100, verbose_name="نام")
    text = models.TextField(verbose_name="نظر")
    email = models.EmailField(max_length=100, verbose_name="ایمیل")
    date = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ")
    active = models.BooleanField(default=False, verbose_name="فعال / غیرفعال")

    objects = CommentManager()

    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"

    def __str__(self):
        return f"{self.blog} - {self.name}"

site_blog/forms.py
from django import forms
from django.core import validators


class CommentForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "لطفا نام خود را وارد کنید *", "class": "form-control",
                   "oninvalid": "setCustomValidity('فیلد را پر کنید')"}),
        label="نام", required=True,
        validators=[validators.MaxLengthValidator(100, "نام و نام خانوادگی شما نمی تواند بیشتر از 100 کارکتر باشد"), ]
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": " * لطفا ایمیل خود را وارد کنید", "class": "form-control",
                                       "oninvalid": "setCustomValidity('فیلد را پر کنید یا ایمیل را درست وارد کنید')"}),
        label="ایمیل", required=True,
        validators=[validators.EmailValidator("ایمیل وارد شده نادرست است")]
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={"placeholder": "لطفا متن نظر خود را وارد کنید *", "class": "form-control textarea", "rows": "4",
                   "id": "commentForm",
                   "tabindex": "tabindex",
                   "oninvalid": "setCustomValidity('فیلد را پر کنید')"}),
        label="متن نظر", required=True
    )

site_blog/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView
from site_about_us.models import AboutUs
from .models import Blogs, Comment
from .forms import CommentForm
from site_blog_category.models import BlogsCategory


class BlogsList(ListView):
    template_name = "blog/blog_list.html"
    paginate_by = 6

    def get_queryset(self):
        return Blogs.objects.get_active_blogs().order_by("-id")


class BlogsListCategory(ListView):
    template_name = "blog/blog_list.html"
    paginate_by = 6

    def get_queryset(self):
        category_name = self.kwargs["category_name"]
        category = BlogsCategory.objects.filter(name__iexact=category_name).first()
        if category is None:
            raise Http404("صفحه ی مورد نظر یافت نشد")
        return Blogs.objects.get_blogs_by_category(category_name)

    def get_context_data(self, **kwargs):
        category_name = self.kwargs["category_name"]
        category = BlogsCategory.objects.filter(name__iexact=category_name).first()
        context = super().get_context_data(**kwargs)
        context["category"] = category

        return context


def blog_detail(request, *args, **kwargs):
    blog_id = kwargs["blogId"]
    blogs = Blogs.objects.get_by_id(blog_id)
    if blogs is None or not blogs.active:
        raise Http404("بلاگی مورد نطر یافت نشد")
    about_us = AboutUs.objects.first()
    comment: Comment = Comment.objects.filter(blog_id=blog_id, active=True)
    comment_count = len(comment)
    comment_form = CommentForm(request.POST or None)

    if comment_form.is_valid():
        name = comment_form.cleaned_data.get("name")
        email = comment_form.cleaned_data.get("email")
        text = comment_form.cleaned_data.get("text")
        Comment.objects.create(name=name, email=email, text=text, blog_id=blog_id)
        return HttpResponseRedirect(blogs.get_absolute_url())
    context = {
        "blogs": blogs,
        "about_us": about_us,
        "comment": comment,
        "comment_form": comment_form,
        "comment_count": comment_count,

    }
    return render(request, "blog/blog_detail.html", context)


def blogs_category_partial(request):
    categories = BlogsCategory.objects.all()
    context = {
        "categories": categories
    }
    return render(request, "blog/blogs_category_partial.html", context)


def like(request, *args, **kwargs):
    blog_id = kwargs["blogId"]
    post = Blogs.objects.get(id=blog_id)
    user = request.user
    if user.is_authenticated:
        if user in post.like.all():
            return HttpResponse("you are like this post!")
        post.like.add(user)
        return redirect(Blogs.objects.get_by_id(blog_id))
    # todo: redirect to login page


def unlike(request, *args, **kwargs):
    blog_id = kwargs["blogId"]
    post = Blogs.objects.get(id=blog_id)
    user = request.user
    if user.is_authenticated:
        if user in post.like.all():
            post.like.remove(user)
            return redirect(Blogs.objects.get_by_id(blog_id))
        else:
            return HttpResponse("you are not like this post!")
    # todo: redirect to login page

site_blog/templates/blog/blog_detail.html
{% extends "shared/_Mainlayout.html" %}
{% block title %}وبلاگ | {{ blogs.title }} - {{ blogs.id }}{% endblock %}
{% load static %}
{% load jalali_tags %}
{% block content %}
    <div class="box box-content">
        <!-- Post -->
        <div class="pb-3">
            <header class="header-post">
                <h1 class="title title--h1">{{ blogs.title }}</h1>
                <div class="caption-post">
                    <p>{{ blogs.description }}</p>
                </div>
                <div class="header-post__image-wrap">
                    <img class="cover medium-zoom-image ls-is-cached lazyloaded" src="{{ blogs.get_image_or_default }}"
                         data-zoom="" alt="{{ blogs.title }}">
                </div>
            </header>
            <div class="caption-post">
                {{ blogs.body|safe }}
            </div>
            <footer class="footer-post">
                <a class="footer-post__share" href="http://facebook.com/{{ about_us.facebook }}"><i
                        class="font-icon icon-facebook"></i><span>فیس بوک</span></a>
                <a class="footer-post__share" href="http://twitter.com/{{ about_us.twitter }}"><i
                        class="font-icon icon-twitter"></i><span>توییتر</span></a>
                <a class="footer-post__share" href="http://instagram.com/{{ about_us.instagram }}"><i
                        class="font-icon icon-instagram"></i><span>اینستاگرام</span></a>
                {% if user.is_authenticated %}
                    {% if user in blogs.like.all %}
                        <a class="footer-post__share" href="{% url "blogs:unlike_blog" blogs.id %}"><i
                                class="font-icon icon-like-fill" style="color: red"></i><span>پس گرفتن لایک</span></a>
                    {% else %}
                        <a class="footer-post__share" href="{% url "blogs:like_blog" blogs.id %}"><i
                                class="font-icon icon-like"></i><span>لایک</span></a>
                    {% endif %}
                {% endif %}

            </footer>
        </div>
        <!-- Comment -->
        <div class="box-inner box-inner--rounded">
            <h2 class="title title--h3">نظرات <span class="color--light">({{ comment_count }})</span></h2>

            <!-- Comment -->
            <div class="comment-box">
                {% for comment in comment %}
                    <div class="comment-box__inner">

                        <div class="comment-box__body">
                            <h5 class="comment-box__details"><span>{{ comment.name }}</span>
                                <span class="comment-box__details-date">تاریخ : {{ comment.date|to_jalali:'%y/%m/%d' }}  | ساعت : {{ comment.date|to_jalali:'%H:%M' }}</span>
                            </h5>
                            <p>{{ comment.text }}</p>

                            {% comment %}
                            <ul class="comment-box__footer">
                                <li><i class="font-icon icon-like-fill"></i> <span>80</span></li>
                            </ul>
{% endcomment %}
                            <hr>
                        </div>

                    </div>
                {% endfor %}

                <!-- Comment form -->
                <ul class="social-auth">
                    <li class="social-auth__item">من رو دنبال کنید :</li>
                    <li class="social-auth__item"><a class="social-auth__link"
                                                     href="http://instagram.com/{{ about_us.facebook }}"><i
                            class="font-icon icon-facebook"></i></a></li>
                    <li class="social-auth__item"><a class="social-auth__link"
                                                     href="http://instagram.com/{{ about_us.twitter }}"><i
                            class="font-icon icon-twitter"></i></a></li>
                    {#                    <li class="social-auth__item"><a class="social-auth__link" href="#"><i#}
                    {#                            class="font-icon icon-dribbble"></i></a></li>#}
                    <li class="social-auth__item"><a class="social-auth__link"
                                                     href="http://instagram.com/{{ about_us.instagram }}"><i
                            class="font-icon icon-instagram"></i></a></li>
                </ul>
                <form class="comment-form" method="post">
                    {% csrf_token %}

                    {#                <textarea id="commentForm" class="textarea form-control" required="required"#}
                    {#                          placeholder="نوشتن دیدگاه ..." rows="1" tabindex="1"#}
                    {#                          style="overflow: hidden; overflow-wrap: break-word; outline: none; touch-action: none; height: 61px;"></textarea>#}
                    {{ comment_form.name }}
                    {{ comment_form.email }}
                    {{ comment_form.text }}
                    <div class="row">
                        <button type="submit"
                                style="margin-top: 20px;background-color: #007bff;border-radius: 20px;border: 2px solid #3B4B5E ;color: #fff;padding: 5px"
                                class="btn-block">ثبت نظر <i
                                class="font-icon icon-send" style="color: #fff"></i>
                        </button>
                    </div>

                    {% comment %}
                    <div class="dropdown dropup">
                        <i class="font-icon icon-smile" id="dropdownEmoji" data-toggle="dropdown"
                           aria-haspopup="true"></i>
                        <div class="dropdown-menu dropdown-menu-center" aria-labelledby="dropdownEmoji">
                            <div class="emoji-wrap">
                                <img class="emoji" src="{% static "icons/emoji/emoji-laughing.svg" %}"
                                     title=":laughing:"
                                     alt="laughing">
                                <img class="emoji" src="{% static "icons/emoji/emoji-happy-2.svg" %}" title=":happy 2:"
                                     alt="happy 2">
                                <img class="emoji" src="{% static "icons/emoji/emoji-crazy.svg" %}" title=":crazy:"
                                     alt="crazy">
                                <img class="emoji" src="{% static "icons/emoji/emoji-bad.svg" %}" title=":bad:"
                                     alt="bad">
                                <img class="emoji" src="{% static "icons/emoji/emoji-angry.svg" %}" title=":angry:"
                                     alt="angry">
                                <img class="emoji" src="{% static "icons/emoji/emoji-happy.svg" %}" title="happy"
                                     alt="happy">
                                <img class="emoji" src="{% static "icons/emoji/emoji-thinking.svg" %}"
                                     title=":thinking:"
                                     alt="thinking">
                                <img class="emoji" src="{% static "icons/emoji/emoji-sad.svg" %}" title=":sad:"
                                     alt="sad">
                                <img class="emoji" src="{% static "icons/emoji/emoji-pressure.svg" %}"
                                     title=":pressure:"
                                     alt="pressure">
                                <img class="emoji" src="{% static "icons/emoji/emoji-in-love.svg" %}" title=":in love:"
                                     alt="in love">
                                <img class="emoji" src="{% static "icons/emoji/emoji-nerd.svg" %}" title=":laughing:"
                                     alt="nerd">
                                <img class="emoji" src="{% static "icons/emoji/emoji-happy-3.svg" %}" title=":happy 3:"
                                     alt="happy 3">
                                <img class="emoji" src="{% static "icons/emoji/emoji-shocked.svg" %}" title=":shocked:"
                                     alt="shocked">
                                <img class="emoji" src="{% static "icons/emoji/emoji-wink.svg" %}" title=":wink:"
                                     alt="wink">
                                <img class="emoji" src="{% static "icons/emoji/emoji-sweating.svg" %}"
                                     title=":sweating:"
                                     alt="sweating">
                                <img class="emoji" src="{% static "icons/emoji/emoji-shocked-2.svg" %}"
                                     title=":shocked 2:"
                                     alt="shocked 2">
                                <img class="emoji" src="{% static "icons/emoji/emoji-shocked-3.svg" %}"
                                     title=":shocked 3:"
                                     alt="shocked 3">
                                <img class="emoji" src="{% static "icons/emoji/emoji-sad-2.svg" %}" title=":sad 2:"
                                     alt="sad 2">
                            </div>
                        </div>
                    </div>
{% endcomment %}
                </form>

            </div>
        </div>
    </div>

{% endblock %}

site_blog/templates/blog/blog_list.html
{% extends "shared/_Mainlayout.html" %}
{% load jalali_tags %}
{% load render_partial %}
{% block title %}وبلاگ من {{ category }}{% endblock %}

{% block content %}

    <div class="box box-content">
        <div class="pb-2">
            <h1 class="title title--h1 first-title title__separate">وبلاگ</h1>
        </div>
    {% render_partial "site_blog.views.blogs_category_partial" %}
        <!-- News -->
        <div class="news-grid">
            <!-- Post -->
            {% for blog in page_obj %}
                <article class="news-item box">
                    <div class="news-item__image-wrap overlay overlay--45">
                        <div class="news-item__date">{{ blog.time|to_jalali:'%H:%M' }}<span>{{ blog.time|to_jalali:'%y/%m/%d' }}</span>
                        </div>
                        <a class="news-item__link" href="{{ blog.get_absolute_url }}"></a>
                        <img class="cover ls-is-cached lazyloaded" src="{{ blog.get_image_or_default }}"
                             alt="{{ blog.time }}">
                    </div>
                    <div class="news-item__caption">
                        <a class="text-decoration-none" href="{{ blog.get_absolute_url }}"><h2
                                class="title title--h4">{{ blog.title }}</h2></a>
                        <a style="color:#2b2b2b;" class="text-decoration-none" href="{{ blog.get_absolute_url }}"><p
                                class="text-justify">{{ blog.description|truncatechars:110 }}</p></a>
                    </div>
                </article>
            {% endfor %}


        </div>

        <div class="pagination-area">
            {% if page_obj|length > 0 %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li style="padding-left: 10px"><a style="color: #fd7e14"
                                                          href="?page={{ page_obj.previous_page_number }}">قبلی</a>
                        </li>
                    {% endif %}
                    {% for page in paginator.page_range %}
                        {% if page == page_obj.number %}
                            <li style="padding-left: 10px;"><a style="color: #304CFD"
                                                               href="?page={{ page }}">{{ page }}</a></li>
                        {% else %}
                            <li style="padding-left: 10px;"><a style="color: #fd7e14"
                                                               href="?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li style="padding-left: 10px"><a style="color: #fd7e14"
                                                          href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                    {% endif %}
                </ul>
            {% else %}
                <p class="alert alert-warning text-center">بلاگ مورد نظر یافت نشد</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

site_blog/templates/blog/blogs_category_partial.html
<ul class="nav list-unstyled mb-2">
    <li class="px-2"><a class="decoration--none" style="color: #5E6E80" href="{% url "blogs:blog_list" %}">همه</a></li>
    {% for category in categories %}
        <li class="px-2"><a
                class="decoration--none" style="color: #0c5460"
                href="{{ category.get_category_url }}">{{ category.title }}</a></li>
    {% endfor %}
</ul>