personal_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from personal_site import settings

urlpatterns = [
    path('', include("site_about_us.urls", namespace="about_us")),
    path('', include("site_resume.urls", namespace="resumes")),
    path('', include("site_blog.urls", namespace="blogs")),
    path('', include("site_work.urls", namespace="works")),
    path('', include("site_contact.urls", namespace="contact")),
    path('admin/', admin.site.urls),
]
handler404 = 'personal_site.views.view_404'
handler403 = 'personal_site.views.view_403'
handler400 = 'personal_site.views.view_400'
handler500  = 'personal_site.views.view_500'

if settings.DEBUG:
    # ADD ROOT STATIC FILES
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # ADD MEDIA STATIC FILES
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_about_us/urls.py
from django.urls import path
from .views import about_me

app_name = "about_us"

urlpatterns = [
    path('', about_me, name="about_me"),
]

site_blog/urls.py
from django.urls import path
from .views import BlogsList, blog_detail, BlogsListCategory, like, unlike

app_name = "blogs"

urlpatterns = [
    path('blogs/', BlogsList.as_view(), name="blog_list"),
    path('blogs/<category_name>/', BlogsListCategory.as_view(), name="blog_list_category"),
    path('blogs/<blogId>/<name>/', blog_detail, name="blog_list"),
    path('like/<blogId>/', like, name="like_blog"),
    path('unlike/<blogId>/', unlike, name="unlike_blog")
]

site_contact/urls.py
from django.urls import path
from .views import contact, success_contact

app_name = "contact"

urlpatterns = [
    path('contact/', contact, name="contact"),
    path('success-send-message/', success_contact, name="success_contact"),
]

site_resume/urls.py
from django.urls import path
from .views import resume

app_name = "resumes"

urlpatterns = [
    path('resume/', resume, name="resume")
]

site_work/urls.py
from django.urls import path
from .views import WorkList

app_name = "works"

urlpatterns = [
    path("works/", WorkList.as_view(), name="work_list")
]

templates/shared/Footer.html
<footer class="footer">{{ setting.footer }}</footer>

templates/shared/Header.html
{% load static %}
<header class="header box">
    <div class="header__left">
        <div class="header__photo">
            <img class="header__photo-img" src="{{ about_us.get_image_or_default }}" alt="Ronald Robertson">
        </div>
        <div class="header__base-info">
            <h4 class="title titl--h4">{{ about_us.first_name }} {{ about_us.last_name }}</h4>
            <div class="status">{{ about_us.short_description }}</div>
            <ul class="header__social">
                <li><a href="https://www.linkedin.com/{{ about_us.facebook }}"><i class="font-icon icon-linkedin1"></i></a>
                </li>
                <li><a href="https://www.twitter.com/{{ about_us.twitter }}"><i class="font-icon icon-twitter1"></i></a>
                </li>
                <li><a href="https://www.instagram.com/{{ about_us.instagram }}"><i
                        class="font-icon icon-instagram1"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="header__right">
        <ul class="header__contact">
            <li><span class="overhead">ایمیل</span>{{ about_us.email }}</li>
            <li><span class="overhead">تلفن</span>{{ about_us.phone }}</li>
        </ul>
        <ul class="header__contact">
            <li><span class="overhead">تولد</span>{{ about_us.date_of_birth }}</li>
            <li><span class="overhead">مکان تولد</span>{{ about_us.place_of_birth }}</li>
        </ul>
    </div>
</header>

templates/shared/_FooterReferences.html
{% load static %}
<!-- JavaScripts -->
<script src="{% static "js/jquery-3.4.1.min.js" %}"></script>
<script src="{% static "js/plugins.min.js" %}"></script>
<script src="{% static "js/common.js" %}"></script>

<!-- Mapbox init -->
<script src="js/mapbox.init.js{% static "images/social.html" %}"></script>
<script src="demo/plugins-demo.js{% static "images/social.html" %}"></script>

templates/shared/_HeaderReferences.html
{% load static %}
<!-- Meta Data -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="format-detection" content="telephone=no"/>
<meta name="format-detection" content="address=no"/>
<meta name="author" content="Melika Khaliliyan"/>
<meta name="description" content="vCard"/>

<!-- Twitter data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@aliniyazi_">
<meta name="twitter:title" content="vCard">
<meta name="twitter:description" content="vCard">
<meta name="twitter:image" content="{% static "images/social.html" %}">

<!-- Open Graph data -->
<meta property="og:title" content="Melika Khaliliyan"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="your url website"/>
<meta property="og:image" content="{% static "images/social.html" %}"/>
<meta property="og:description" content="vCard"/>
<meta property="og:site_name" content="vCard"/>

<!-- Favicons -->
<link rel="apple-touch-icon" sizes="144x144" href="{% static "images/favicons/apple-touch-icon-144x144.png" %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static "images/favicons/apple-touch-icon-114x114.png" %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static "images/favicons/apple-touch-icon-72x72.png" %}">
<link rel="apple-touch-icon" sizes="57x57" href="{% static "images/favicons/apple-touch-icon-57x57.png" %}">
<link rel="shortcut icon" href="{{ setting.get_image_or_default }}" type="image/png">

<!-- Styles -->
<link rel="stylesheet" type="text/css" href="{% static "styles/style-rtl-demo.css" %}"/>
<link rel="stylesheet" type="text/css" href="{% static "styles/style-rtl.css" %}"/>
<link rel="stylesheet" type="text/css" href="{% static "demo/style-demo.css" %}"/>
<!-- Mapbox-->
<script src="{% static "js/mapbox-gl.js" %}"></script>
<link rel="stylesheet" href="{% static "styles/mapbox-gl.css" %}">

templates/shared/_Mainlayout.html
{% load render_partial %}
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>

    {% render_partial "personal_site.views.header_references" %}

</head>
<body>
<!-- Preloader -->
<div class="preloader">
    <div class="preloader__wrap">
        <div class="circle-pulse">
            <div class="circle-pulse__1"></div>
            <div class="circle-pulse__2"></div>
        </div>
        <div class="preloader__progress"><span></span></div>
    </div>
</div>

<main class="main">
    <!-- Header Image -->
    {% render_partial "personal_site.views.header_image_background" %}

    <div class="container gutter-top">
        <!-- Header -->
        {% render_partial "personal_site.views.header" %}

        <div class="row sticky-parent">
            <!-- Sidebar nav -->
            <aside class="col-12 col-md-12 col-lg-2">
                <div class="sidebar box sticky-column">
                    <ul class="nav">
                        <li class="nav__item"><a
                                class="{% if request.path == "/" %}active{% endif %}"
                            href="{% url "about_us:about_me" %}"><i
                                    class="icon-user"></i>درباره ی
                            من</a></li>
                        <li class="nav__item"><a class="{% if request.path == "/resume/" %}active{% endif %}"
                            href="{% url "resumes:resume" %}"><i
                                    class="icon-file-text"></i>رزومه</a></li>
                        <li class="nav__item"><a class="{% if request.path == "/works/" %}active{% endif %}"
                            href="{% url "works:work_list" %}"><i class="icon-codesandbox"></i>
                            کارها</a></li>
                        <li class="nav__item"><a class="{% if request.path == "/blogs/" %}active{% endif %}"
                            href="{% url "blogs:blog_list" %}"><i class="icon-book-open"></i>وبلاگ</a>
                        </li>
                        <li class="nav__item"><a class="{% if request.path == "/contact/" %}active{% endif %}"
                            href="{% url "contact:contact" %}"><i class="icon-book"></i>تماس با ما</a>
                        </li>
                    </ul>
                </div>
            </aside>
            <!-- Content -->
            <div class="col-12 col-md-12 col-lg-10">
                {% block content %}

                {% endblock %}
                <!-- Footer -->
                {% render_partial "personal_site.views.footer" %}
            </div>
        </div>
    </div>
</main>

<div class="back-to-top"></div>

<!-- SVG masks -->
<svg class="svg-defs">
    <clipPath id="avatar-box">
        <path d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z"/>
    </clipPath>
    <clipPath id="avatar-hexagon">
        <path d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z"/>
    </clipPath>
</svg>

<!-- Demo Menu -->
{% comment %}
<div class="btnSlideNav slideOpen"></div>
<div class="btnSlideNav slideClose"></div>
<div class="slideNav">
    <ul class="list-unstyled">
        <li class="slideNav__item rtl-mode"><h4 class="title title--5">صفحات بیشتر</h4> <a href="ltr/about.html">نسخه چپ
            چین</a></li>
        <li class="slideNav__item"><a href="one-page.html">صفحه تکی</a></li>
        <li class="slideNav__item"><a href="background-2.html">پس زمینه مثلثی</a></li>
        <li class="slideNav__item"><a href="works_v2.html">نمونه کارها نسخه 2</a></li>
    </ul>
    <a href="dark/about.html" class="btn btn--dark">نسخه تیره</a>
</div>
<div class="overlay-slideNav"></div>
{% endcomment %}
<!-- Demo Menu -->

{% include "shared/_FooterReferences.html" %}
</body>
</html>

templates/shared/header_image_background.html
{% load static %}
<div class="header-image">
    <div class="js-parallax" style="background-image: url({{ background_image.get_image_or_default }});"></div>
</div>